spring:
  profiles:
    active:
    - dev
spring:
  profiles: dev #开发环境
  application:
      name: microservicecloud-config-zwh-dev
spring:
  profiles: test
  application:
      name: microservicecloud-config-zwh-test
